### ISSUE TITLE
Switch "Concept" label to "Research Area"

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/rialto-derivatives#164]
This should then change the label display in the web app in the facets and the counts in the header

**Comment by peetucket** [comment]
ok, @justinlittman suggested I create here, but that's fine too

**Comment by mjgiarlo** [comment]
I deleted my comment and decided that it's best to make the change in both places. I was mistaken that this could be fixed only in webapp. There are now two PRs for this pending.
