### ISSUE TITLE
Index complex properties of Publication

### ISSUE THREAD

**Issue by jcoyne** [sul-dlss/rialto-derivatives#17]
e.g.:
author 	vivo:relatedBy vivo:Authorship vivo:relates 	URI for foaf:Agent 	[0,n] 	Author of the publication.
Profiles confirmed 	vivo:relatedBy vivo:Authorship dcterms:source 	"Profiles" string-literal 	[0,1] 	If the authorship relationship has been confirmed by the Author in Profiles. Can be reused for any relationship needed (i.e. Editorship, Advising Relationship, etc.)
editor 	vivo:relatedBy vivo:Editorship vivo:relates 	URI for foaf:Agent 	[0,n] 	Editor of the publication.
```


See: https://github.com/sul-dlss/rialto/wiki/RIALTO-Data-Models-&-Profiles#publications-aka-documents-or-citations

**Comment by justinlittman** [comment]
Currently implementing all properties necessary for requirements.
